version: '3.8'

services:
  blog-api:
    build: ./backend
    container_name: blog-api
    env_file: .env
    ports:
      - "8002:8000"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  blog-web:
    image: nginx:alpine
    container_name: blog-web
    ports:
      - "8082:80"
    volumes:
      - ./frontend:/usr/share/nginx/html