version: '3.8'

services:
  notes-api:
    build: ./backend
    container_name: notes-api
    env_file: .env
    ports:
      - "8005:8000"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  notes-web:
    image: nginx:alpine
    container_name: notes-web
    ports:
      - "8085:80"
    volumes:
      - ./frontend:/usr/share/nginx/html