version: '3.8'

services:
  shop-api:
    build: ./backend
    container_name: shop-api
    env_file: .env
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  shop-web:
    image: nginx:alpine
    container_name: shop-web
    ports:
      - "8081:80"
    volumes:
      - ./frontend:/usr/share/nginx/html