version: '3.8'

services:
  movies-api:
    build: ./backend
    container_name: movies-api
    env_file: .env
    ports:
      - "8003:8000"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  movies-web:
    image: nginx:alpine
    container_name: movies-web
    ports:
      - "8083:80"
    volumes:
      - ./frontend:/usr/share/nginx/html